var listOfWords = ["knicks", 
'hawks', 
'celtics', 
'nets',
'bobcats', 
'bulls', 
'Cavaliers', 
'mavericks', 
'nuggets', 
'pistons', 
'warriors', 
'rockets', 
'pacers', 
'clippers', 
'lakers', 
'grizzlies', 
'heat', 
'bucks', 
'Timberwolves', 
'hornets', 
'knicks', 
'thunder', 
'magic', 
'sixers', 
'suns', 
'blazers', 
'kings', 
'spurs', 
'raptors', 
'jazz', 
'wizards'];

// Export the list of words to other hangman script(s)
module.exports = listOfWords;

// "steph curry", "basketball", "dunk", "kevin durant", "court", "jumper", "kyrie irving", "james harden", "warriors"